### ISSUE TITLE
pingora用0.4.0版本，编译出现错误，用0.3.0编译是可以的

### ISSUE THREAD

**Issue by yeungsean** [caibirdme/penguin#19]
~/penguin > cargo build
   Compiling penguin v0.1.0 (/home/yeungsean/project/rust/penguin)
error[E0063]: missing field `ext` in initializer of `Backend`
  --> src/clusters/discovery/mod.rs:80:23
   |
80 |             .map(|ip| Backend {
   |                       ^^^^^^^ missing `ext`

For more information about this error, try `rustc --explain E0063`

**Comment by caibirdme** [comment]
Thx I'll fix it asap

**Comment by caibirdme** [comment]
it's fixed
